# Generated by Django 5.1.3 on 2024-12-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('marital_status', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=255)),
                ('orders', models.IntegerField()),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
